version: '2.1'
services:
  crossblogs-app:
    image: crossblogs
    ports:
    - 8080:8080
    depends_on:
      crossblogs-mysql:
        condition: service_healthy
  crossblogs-mysql:
    extends:
      file: mysql.yml
      service: crossblogs-mysql