version: '3.3'

services:
  api:
    image: crossblogs
    environment:
      MYSQL_HOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7.20
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=crossblogs
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
